# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'  # Specify minimum iOS version

target 'example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example
  pod 'PhoneNumberKit', '~> 4.0.1'

  #* Add VerifySpeed_IOS_SDK
  pod 'VerifySpeed_IOS_SDK', '~> 1.0.22'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
